---
date-modified: last-modified
pagetitle: Welcome
---

# Welcome {.unnumbered}

## CORTRE – COmplete Reporting for Transparent Reproducibility Efforts 

::: {.callout-tip}
## Aim
To develop a consensus-based reporting guideline for reproduciblity efforts -- projects that systematically re-examine previously published findings or previously tested hypotheses.
:::

Efforts investigating reproducibility, replicability, robustness, generalisability, or related concepts, whether across entire fields, research methods, study types, or journal articles, have an important influence on science policy, trajectory, and public trust in research. Examples of such efforts include large replication projects in psychology ([RPP](https://osf.io/ezcuj/){.external target="_blank"}), cancer biology ([RPCB](https://www.cos.io/rpcb){.external target="_blank"}), experimental economics ([RPEE](https://doi.org/10.1126/science.aaf0918){.external target="_blank"}), as well as investigations into the robustness and/or computational reproducibility of results published in specific journals (e.g., [Institute for Replication](https://i4replication.org/){.external target="_blank"}). Some reproducibility efforts have reported alarming results, and their papers are frequently cited in calls for science policy reforms and interventions, such as mandates for data and code sharing or preregistration. 

Research that informs policy must be of the highest possible quality, reliable, and trustworthy. The type of study that we refer to here, a reproducibility effort, is relatively new and rapidly evolving. Their data are frequently re-analysed, e.g., using novel metrics and methods to aggregate and contextualise results. Metaresearchers might also want to synthesise results from multiple efforts to draw conclusions that extend beyond each individual efforts. All of these endeavours depend on transparent, high-quality reporting. To our knowledge, no reporting guideline exists at present for reproducibility efforts.

To address this gap, the CORTRE team convened at the Responsible Research in Action Unconference in Berlin (<https://rr-in-action2025.org/>{.external target="_blank"}) to conceptualise and launch an initiative to create such a reporting guideline. Since then, we have been following the EQUATOR toolkit for developing reporting guidelines, including initial list creation. We currently plan a Delphi study, followed by a face-to-face meeting for consensus finding. To this end, we have submitted a Stage 1 Registered Report (<https://doi.org/10.31222/osf.io/6wj82_v1>{.external target="_blank"}).


Once developed, we hope that our reporting guideline will also be useful to those designing or assessing future reproducibility efforts. We welcome additional researchers interested in joining the project.

**Contact:** Rachel Heyard on behalf of the CORTRE steering committee, Center for Reproducible Science and Research Synthesis, University of Zurich, Switzerland. Email: <rachel.heyard@uzh.ch>. 

::: {.callout-note}
## Note
Our intent to develop a reporting guideline was [registered on the website of the EQUATOR Network](https://www.equator-network.org/library/reporting-guidelines-under-development/reporting-guidelines-under-development-for-other-study-designs/#CORTRE){.external target="_blank"}. Note that since then, the scope of the reporting guideline has developed to also include small-scale reproducibility efforts.
:::



 
